version: '3.4'

services:
  service.api:
    image: service.api
    build:
      context: .
      dockerfile: Service.Api/Dockerfile
    ports:
      - "20000:80"
    networks:
      - docker-network
    depends_on:
      - "sql"  
  sql:
    image: "microsoft/mssql-server-linux:latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "@jeanN3550!"
      ACCEPT_EULA: "Y"  
    networks:
      - docker-network  
networks: 
    docker-network:
        driver: bridge      
